# Generated by Django 5.2.14 on 2026-05-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField(help_text='Valore numerico (es. peso in kg, distanza in km, numero reps)')),
                ('notes', models.TextField(blank=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='goals.goal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
