# Generated by Django 6.0.6 on 2026-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('standard', 'Utente Standard'), ('coach', 'Coach')], default='standard', max_length=20),
        ),
    ]
