# Generated by Django 5.2.14 on 2026-05-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('generic', 'Generico'), ('metric', 'A Metrica')], default='generic', max_length=20)),
                ('metric', models.CharField(blank=True, choices=[('weight', 'Peso (kg)'), ('distance', 'Distanza (km)'), ('reps', 'Ripetizioni')], max_length=20, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Attivo'), ('completed', 'Completato'), ('abandoned', 'Abbandonato')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
